# Generated by Django 4.0 on 2022-01-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strengh', models.IntegerField()),
                ('inteligence', models.IntegerField()),
                ('dextrity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('enterance_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('strengh', models.IntegerField()),
                ('inteligence', models.IntegerField()),
                ('dextrity', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('health_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inteligence', models.IntegerField()),
                ('strengh', models.IntegerField()),
                ('dextrity', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('health_point', models.IntegerField()),
                ('travel_sustain', models.IntegerField()),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler_games.land')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='land',
            name='monster_set',
            field=models.ManyToManyField(to='traveler_games.Monster'),
        ),
    ]
