# Generated by Django 4.0 on 2022-01-21 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('doc',)},
        ),
        migrations.AddField(
            model_name='player',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='damage',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='player',
            name='dextrity',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='health_point',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='inteligence',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='strengh',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='travel_sustain',
            field=models.IntegerField(default=10),
        ),
    ]
