# Generated by Django 4.0 on 2022-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveler_games', '0002_alter_player_options_player_doc_alter_player_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
