# Generated by Django 4.0 on 2022-01-22 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveler_games', '0003_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='localization',
            field=models.ForeignKey(default=9788992, on_delete=django.db.models.deletion.CASCADE, to='traveler_games.land'),
        ),
    ]
