# Generated by Django 3.2.6 on 2021-09-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anwsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Poll_part',
        ),
        migrations.AddField(
            model_name='anwsers',
            name='first_anws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_anws1', to='my_polls.question'),
        ),
        migrations.AddField(
            model_name='anwsers',
            name='fourth_anws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_anws4', to='my_polls.question'),
        ),
        migrations.AddField(
            model_name='anwsers',
            name='second_anws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_anws2', to='my_polls.question'),
        ),
        migrations.AddField(
            model_name='anwsers',
            name='third_anws',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_anws3', to='my_polls.question'),
        ),
    ]
